# ICEMET Sensor config
#

# Files
save: {
dir: "~/.icemet",
type: "png"
}

# Measurement settings
measurement: {
fps: 1,
len: 60
}

# Sensor settings
sensor: {
id: 1,
restart: -1
}

# Cameras: dummy{}, spin{id}, pylon{}
camera: {"spin": {
"id": 0
}}

# Lasers: dummy{}, picolas{port}, icemet{}
laser: {"icemet": {}}

# FTP settings
ftp: {
host: "localhost",
port: 21,
user: "icemet",
passwd: "",
path: "."
}

# Preprocessing
preproc: {
enable: false,
crop: {x: 200, y: 0, w: 2048, h: 2048},
rotate: 0,
empty: {th_original: 40, th_preproc: 10},
bgsub_stack_len: 7
}
